version: '3.4'

services:
  web:
    image: parts_catalogue_demo
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: adminss
      POSTGRES_USER: postgres-admin
      POSTGRES_DB: parts_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data